function add_tx_io(hRD)

% add AXI4 and AXI4-Lite slave interfaces
hRD.addAXI4SlaveInterface( ...
    'InterfaceConnection', 'axi_cpu_interconnect/M20_AXI', ...
    'BaseAddress',         '0x43C00000', ...
    'MasterAddressSpace',  'sys_ps7/Data');
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%	
% Tx Reference design interfaces
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%	

hRD.addInternalIOInterface( ...
    'InterfaceID',    'IP Data 0 IN', ...
    'InterfaceType',  'IN', ...
    'PortName',       'axi_ltc2387_0_adc_data', ...
    'PortWidth',      16, ...
    'InterfaceConnection', 'axi_ltc2387_0/adc_data', ...
    'IsRequired',     false);

hRD.addInternalIOInterface( ...
    'InterfaceID',    'IP Data 1 IN', ...
    'InterfaceType',  'IN', ...
    'PortName',       'axi_ltc2387_1_adc_data', ...
    'PortWidth',      16, ...
    'InterfaceConnection', 'axi_ltc2387_1/adc_data', ...
    'IsRequired',     false);

hRD.addInternalIOInterface( ...
    'InterfaceID',    'IP Data 2 IN', ...
    'InterfaceType',  'IN', ...
    'PortName',       'axi_ltc2387_2_adc_data', ...
    'PortWidth',      16, ...
    'InterfaceConnection', 'axi_ltc2387_2/adc_data', ...
    'IsRequired',     false);

hRD.addInternalIOInterface( ...
    'InterfaceID',    'IP Data 3 IN', ...
    'InterfaceType',  'IN', ...
    'PortName',       'axi_ltc2387_3_adc_data', ...
    'PortWidth',      16, ...
    'InterfaceConnection', 'axi_ltc2387_3/adc_data', ...
    'IsRequired',     false);	

hRD.addInternalIOInterface( ...
    'InterfaceID',    'IP Load Tx Data OUT', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'axi_ad3552r_0_valid_in_a', ...
    'PortWidth',      1, ...
    'InterfaceConnection', 'axi_ad3552r_0/valid_in_a', ...
    'IsRequired',     false);	
	
hRD.addInternalIOInterface( ...
    'InterfaceID',    'IP Valid Tx Data IN', ...
    'InterfaceType',  'IN', ...
    'PortName',       'axi_ltc2387_0_adc_valid', ...
    'PortWidth',      1, ...
    'InterfaceConnection', 'axi_ltc2387_0/adc_valid', ...
    'IsRequired',     false);
    
hRD.addInternalIOInterface( ...
    'InterfaceID',    'CN0585 DAC Data 0 OUT', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'axi_ad3552r_0_data_in_a', ...
    'PortWidth',      16, ...
    'InterfaceConnection', 'axi_ad3552r_0/data_in_a', ...
    'IsRequired',     false);
    
hRD.addInternalIOInterface( ...
    'InterfaceID',    'CN0585 DAC Data 1 OUT', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'axi_ad3552r_0_data_in_b', ...
    'PortWidth',      16, ...
    'InterfaceConnection', 'axi_ad3552r_0/data_in_b', ...
    'IsRequired',     false);   
    
hRD.addInternalIOInterface( ...
    'InterfaceID',    'CN0585 DAC Data 2 OUT', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'axi_ad3552r_1_data_in_a', ...
    'PortWidth',      16, ...
    'InterfaceConnection', 'axi_ad3552r_1/data_in_a', ...
    'IsRequired',     false);   
    
hRD.addInternalIOInterface( ...
    'InterfaceID',    'CN0585 DAC Data 3 OUT', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'axi_ad3552r_1_data_in_b', ...
    'PortWidth',      16, ...
    'InterfaceConnection', 'axi_ad3552r_1/data_in_b', ...
    'IsRequired',     false);
    
hRD.addInternalIOInterface( ...
    'InterfaceID',    'GPIO IN SW', ...
    'InterfaceType',  'IN', ...
    'PortName',       'xlslice_1_Dout', ...
    'PortWidth',      8, ...
    'InterfaceConnection', 'xlslice_1/Dout', ...
    'IsRequired',     false);   
    
hRD.addInternalIOInterface( ...
    'InterfaceID',    'GPIO OUT LED', ...
    'InterfaceType',  'OUT', ...
    'PortName',       'xlconcat_1_In1', ...
    'PortWidth',      8, ...
    'InterfaceConnection', 'xlconcat_1/In1', ...
    'IsRequired',     false);                        
